# Stage 0: build java and scala environment
FROM ubuntu:bionic

RUN apt-get update \
    && apt-get install -y \
        software-properties-common \
        curl \
    && rm -rf /var/lib/apt/lists/*

RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections \
    && add-apt-repository -y ppa:webupd8team/java \
    && apt-get update \
    && apt-get install -y oracle-java8-installer \
    && rm -rf /var/cache/oracle-jdk8-installer \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

RUN curl -L -o sbt.deb http://dl.bintray.com/sbt/debian/sbt-0.13.16.deb \
    && dpkg -i sbt.deb \
    && apt-get update \
    && apt-get install -y \
        sbt \
    && rm sbt.deb \
    && rm -rf /var/lib/apt/lists/*
